import LegalPage from "@/components/LegalPage";

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      updated="January 2025"
      sections={[
        ["1. Information We Collect", "We collect information you provide directly (name, email, government ID for KYC), information generated by your use (transaction history, device data), and information from third-party sources (credit bureaus, sanctions lists)."],
        ["2. How We Use Information", "To provide and improve services, verify your identity, prevent fraud, comply with legal obligations, and communicate with you about your account."],
        ["3. Information Sharing", "We do not sell your personal data. We may share information with service providers, regulators, law enforcement (when legally required), and affiliates under strict confidentiality agreements."],
        ["4. Data Retention", "We retain personal data for as long as your account is active and for a minimum of 5 years after closure to comply with applicable law."],
        ["5. Security", "We use AES-256 encryption at rest, TLS 1.3 in transit, hardware security modules for key management, and SOC 2 Type II certified controls."],
        ["6. Your Rights", "Depending on your jurisdiction, you may have rights to access, correct, delete, port, or restrict processing of your personal data."],
        ["7. Cookies", "We use strictly necessary, functional, and analytical cookies. You may manage preferences in the cookie banner."],
        ["8. Contact", "Data Protection Officer: privacy@apexvault.example"],
      ]}
    />
  );
}